"""Notification data model."""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict


@dataclass
class Notification:
    """A single notification generated by a monitor."""

    # Category of the notification
    CATEGORY_INJURY = "injury"
    CATEGORY_MATCHUP = "matchup"
    CATEGORY_INSIGHT = "insight"

    # Severity levels
    SEVERITY_INFO = "info"
    SEVERITY_WARNING = "warning"
    SEVERITY_CRITICAL = "critical"

    category: str  # injury | matchup | insight
    severity: str  # info | warning | critical
    title: str
    body: str
    data: Dict[str, Any] = field(default_factory=dict)
    created_at: str = ""
    read: bool = False
    id: int | None = None  # set by DB after insert

    def __post_init__(self) -> None:
        if not self.created_at:
            self.created_at = datetime.now().isoformat(timespec="seconds")

    # ── Serialisation helpers ──

    def data_json(self) -> str:
        return json.dumps(self.data) if self.data else "{}"

    @staticmethod
    def data_from_json(raw: str | None) -> Dict[str, Any]:
        if not raw:
            return {}
        try:
            return json.loads(raw)
        except (json.JSONDecodeError, TypeError):
            return {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "category": self.category,
            "severity": self.severity,
            "title": self.title,
            "body": self.body,
            "data": self.data,
            "created_at": self.created_at,
            "read": self.read,
        }
